### ISSUE TITLE
Cadence refresh - Roadmap

### ISSUE THREAD

**Issue by mariusbegby** [mariusbegby/cadence#9]
This issue tracks the rewrite of the codebase. The rewrite aims to improve maintainability, testability, and performance by adopting an object-oriented approach with dependency inversion. Key changes include switching to `pnpm` for package management, using `@biomejs/biome` for linting and formatting, and using `eris` instead of `discord.js` to optimize memory usage. Besides this, all code and functionality is being written from scratch.

### Functionality list
- [ ] Unit tests
  - [ ] Common mock utilities: _Create common mocks and utilities used when creating unit tests._
  - [ ] Good coverage: _Aim for high test coverage through unit testing all possible components in the application._
- [ ] Core
  - [x] Application entrypoint: _Starting file (index.ts)._
  - [x] ShardClient: _The client responsible for connecting a set of shards._
  - [ ] ShardManager: _The manager responsible for spawning a set of shard clients to utilize multiple processes._ 
    - Needs clarification with Eris.
  - [x] DeploymentDispatcher: _Manages verification and deployment of application commands to Discord API._
  - [x] CoreValidator: _Responsible for validating critical configuration and required dependencies._
- [ ] Events
  - [ ] Client
    - [ ] guildCreate, interactionCreate, ready, etc.:  _Handle relevant events from discord.js client._
  - [ ] Player
    - [ ] playerStart, playerFinish, willAutoPlay, etc.: _Handle relevant events from discord-player player._
  - [ ] Process
    - [ ] uncaughtException, unhandledRejection, etc.: _Handle relevant events from Node.js process._
  - [x] EventHandlerManager: _Initializes event listeners for the defined event handlers._
- [ ] Interactions
  - [ ] Autocomplete:
    - [ ] Play: _Execution logic for autocomplete trigger in the /play command._
    - [ ] Lyrics: _Execution logic for autocomplete trigger in the /lyrics command._
  - [ ] Component
    - [ ] ButtonPauseResumeTrack: _Execution logic for button component used to pause and resume tracks._
    - [ ] ButtonPreviousTrack: _Execution logic for button component used to go back in queue._
    - [ ] ButtonNextTrack: _Execution logic for button component used to go forward in queue._
    - [ ] ButtonFiltersDisable: _Execution logic for button component used to disable current audio filters._
    - [ ] SelectMenuFilters: _Execution logic for select menu component used to select audio filters._
    - [ ] Others: _Other components not yet planned._
  - [ ] Slashcommand
    - [ ] Back: _Execution logic for the /back slash command._
    - [ ] Filters: _Execution logic for the /filters slash command._
    - [ ] Help: _Execution logic for the /help slash command._
    - [ ] History: _Execution logic for the /history slash command._
    - [ ] Join: _Execution logic for the /join slash command._
    - [ ] Leave: _Execution logic for the /leave slash command._
    - [ ] Loop: _Execution logic for the /loop slash command._
    - [ ] Lyrics: _Execution logic for the /lyrics slash command._
    - [ ] Move: _Execution logic for the /move slash command._
    - [ ] Nowplaying: _Execution logic for the /nowplaying slash command._
    - [ ] Pause: _Execution logic for the /pause slash command._
    - [ ] Play: _Execution logic for the /play slash command._
    - [ ] Queue: _Execution logic for the /queue slash command._
    - [ ] Remove: _Execution logic for the /remove slash command._
    - [ ] Seek: _Execution logic for the /seek slash command._
    - [ ] Settings: _Execution logic for the /settings slash command._
    - [ ] Shards: _Execution logic for the /shards slash command._
    - [ ] Shuffle: _Execution logic for the /shuffle slash command._
    - [ ] Skip: _Execution logic for the /skip slash command._
    - [ ] Status: _Execution logic for the /status slash command._
    - [ ] Stop: _Execution logic for the /stop slash command._
    - [ ] Volume: _Execution logic for the /volume slash command._
  - [x] InteractionHandler: _Responsible for handling incoming interactions and routing them to correct executor._
  - [ ] HookManager: _Manages loading and execution of hooks for interactions._
- [ ] Services
  - [ ] Insights
    - [x] LoggerService: _The logger service used throughout the application._
    - [x] HealthCheckService: _Health check service for managing and running defined health checks._
    - [ ] MetricService: _Service used throughout the application to collect different metrics._
  - [ ] Player
    - [ ] PlayerService: _The service used for interfacing against discord-player._
  - [ ] Security
    - [ ] RateLimitService: _The service used for managing rate limits for users._
  - [ ] Storage
    - [ ] PrismaClient: _Client for prisma ORM._
    - [ ] StorageClient: _The storage client used for storing and retrieving persistent data._
- [ ] Utilities
  - [ ] EmbedHelper: _Helper utility for generating embeds, replies and related data._
  - [ ] LocaleHelper: _Helper utility for translation throughout the bot._
  - [ ] FormattingUtility: _Helper utility for formatting values._
- [ ] Validation
  - [ ] ValidationHandler: _Handles the validators defined in subfolder._
